test exit in fail

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -174,7 +174,8 @@ else
         wget https://ftp.gnu.org/gnu/gsl/gsl-2.4.tar.gz -O - | tar -zx
         cd gsl-2.4
         ./configure --prefix=$PREFIX
-        make -j 1 || make && make install
+        make -j 1 || { echo 'GSL installation failed' ; exit 1; }
+	make install
     else
         echo "####################"
         echo "gsl NOT FOUND"
@@ -198,7 +199,8 @@ else
         wget http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz -O - | tar -zx
         cd nlopt-2.4.2
         ./configure --enable-shared --without-guile --prefix=$PREFIX
-        make -j 1 || make && make install
+        make -j 1 || { echo 'NLOPT installation failed' ; exit 1; }
+        make install
     else
         echo "####################"
         echo "nlopt NOT FOUND"
@@ -222,7 +224,8 @@ else
         wget https://www.open-mpi.org/software/hwloc/v1.11/downloads/hwloc-1.11.5.tar.gz -O - | tar -zx
         cd hwloc-1.11.5
         ./configure --prefix=$PREFIX
-        make -j 1 || make && make install
+        make -j 1 || { echo 'HWLOC installation failed' ; exit 1; }
+        make install
     else
         echo "####################"
         echo "hwloc NOT FOUND"
@@ -250,7 +253,8 @@ else
         else
             ./configure --disable-cuda --disable-opencl --prefix=$PREFIX
         fi
-        make -j 1|| make && make install
+        make -j 1 || { echo 'STARPU installation failed' ; exit 1; }
+        make install
     else
         echo "####################"
         echo "StarPU NOT FOUND"
@@ -275,7 +279,8 @@ else
         cd $BASEDIR/src/hicma/chameleon
         mkdir -p build && cd build
         cmake .. -DCHAMELEON_USE_MPI=$MPIVALUE -DCHAMELEON_USE_CUDA=$CUDAVALUE -DCHAMELEON_ENABLE_EXAMPLE=OFF -DCHAMELEON_ENABLE_TESTING=OFF -DCHAMELEON_ENABLE_TIMING=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$PREFIX   -DBLAS_LIBRARIES="-L${MKLROOT}/lib -Wl,-rpath,${MKLROOT}/lib -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl"
-        make -j 1|| make VERBOSE=1 && make install
+        make -j 1 || { echo 'CHAMELEON installation failed' ; exit 1; }
+        make install
     else
         echo "####################"
         echo "CHAMELEON NOT FOUND"
@@ -298,7 +303,8 @@ else
         cd $BASEDIR/src/stars-h
         mkdir -p build && cd build
         cmake .. -DCMAKE_C_FLAGS=-fPIC -DEXAMPLES=OFF -DTESTING=OFF -DMPI=$MPIVALUE -DCMAKE_INSTALL_PREFIX=$PREFIX
-        make -j  1|| make VERBOSE=1 && make install
+        make -j 1 || { echo 'STARS-H installation failed' ; exit 1; }
+        make install
     else
         echo "####################"
         echo "starsh NOT FOUND"
@@ -321,7 +327,8 @@ else
         cd $BASEDIR/src/hicma/
         mkdir -p build && cd build
         cmake .. -DHICMA_USE_MPI=$MPIVALUE -DBUILD_SHARED_LIBS=ON -DHICMA_ENABLE_TESTING=OFF -DHICMA_ENABLE_TIMING=OFF -DCMAKE_INSTALL_PREFIX=$PREFIX  -DBLAS_LIBRARIES="-L${MKLROOT}/lib -Wl,-rpath,${MKLROOT}/lib -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl"
-        make -j 1 || make VERBOSE=1 && make install
+        make -j 1 || { echo 'HICMA installation failed' ; exit 1; }
+        make install
     else
         echo "####################"
         echo "hicma NOT FOUND"
