test

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -162,79 +162,79 @@ then
 fi
 
 # gsl
-if pkg-config --exists --atleast-version=2 gsl
-then
-    _LOCATION=`pkg-config --variable=prefix gsl`
-    echo "gsl FOUND in [$_LOCATION]"
-else
-    if [ "$BUILD_DEPENDENCIES" == "true" ]
-    then
-        echo "Building GSL..."
-        cd $TMPDIR
-        wget https://ftp.gnu.org/gnu/gsl/gsl-2.4.tar.gz -O - | tar -zx
-        cd gsl-2.4
-        ./configure --prefix=$PREFIX
-        make -j 1 || { echo 'GSL installation failed' ; exit 1; }
-	make install
-    else
-        echo "####################"
-        echo "gsl NOT FOUND"
-        echo "Please download it from: https://ftp.gnu.org/gnu/gsl/gsl-2.4.tar.gz"
-        echo "After installing it, set the proper PKG_CONFIG_PATH variable"
-        echo ""
-        err=1
-    fi
-fi
+#if pkg-config --exists --atleast-version=2 gsl
+#then
+#    _LOCATION=`pkg-config --variable=prefix gsl`
+#    echo "gsl FOUND in [$_LOCATION]"
+#else
+#    if [ "$BUILD_DEPENDENCIES" == "true" ]
+#    then
+#        echo "Building GSL..."
+#        cd $TMPDIR
+#        wget https://ftp.gnu.org/gnu/gsl/gsl-2.4.tar.gz -O - | tar -zx
+#        cd gsl-2.4
+#        ./configure --prefix=$PREFIX
+#        make -j 1 || { echo 'GSL installation failed' ; exit 1; }
+#	make install
+#    else
+#        echo "####################"
+#        echo "gsl NOT FOUND"
+#        echo "Please download it from: https://ftp.gnu.org/gnu/gsl/gsl-2.4.tar.gz"
+#        echo "After installing it, set the proper PKG_CONFIG_PATH variable"
+#        echo ""
+#        err=1
+#    fi
+#fi
 
 # nlopt
-if pkg-config --exists --atleast-version=2.4 nlopt
-then
-    _LOCATION=`pkg-config --variable=prefix nlopt`
-    echo "nlopt FOUND in [$_LOCATION]"
-else
-    if [ "$BUILD_DEPENDENCIES" == "true" ]
-    then
-        echo "Building NLOPT..."
-        cd $TMPDIR
-        wget http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz -O - | tar -zx
-        cd nlopt-2.4.2
-        ./configure --enable-shared --without-guile --prefix=$PREFIX
-        make -j 1 || { echo 'NLOPT installation failed' ; exit 1; }
-        make install
-    else
-        echo "####################"
-        echo "nlopt NOT FOUND"
-        echo "Please download it from: http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz"
-        echo "After installing it, set the proper PKG_CONFIG_PATH variable"
-        echo ""
-        err=1
-    fi
-fi
+#if pkg-config --exists --atleast-version=2.4 nlopt
+#then
+#    _LOCATION=`pkg-config --variable=prefix nlopt`
+#    echo "nlopt FOUND in [$_LOCATION]"
+#else
+#    if [ "$BUILD_DEPENDENCIES" == "true" ]
+#    then
+#        echo "Building NLOPT..."
+#        cd $TMPDIR
+#        wget http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz -O - | tar -zx
+#        cd nlopt-2.4.2
+#        ./configure --enable-shared --without-guile --prefix=$PREFIX
+#        make -j 1 || { echo 'NLOPT installation failed' ; exit 1; }
+#        make install
+#    else
+#        echo "####################"
+#        echo "nlopt NOT FOUND"
+#        echo "Please download it from: http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz"
+#        echo "After installing it, set the proper PKG_CONFIG_PATH variable"
+#        echo ""
+#        err=1
+#    fi
+#fi
 
 # hwloc
-if pkg-config --exists hwloc
-then
-    _LOCATION=`pkg-config --variable=prefix hwloc`
-    echo "hwloc FOUND in [$_LOCATION]"
-else
-    if [ "$BUILD_DEPENDENCIES" == "true" ]
-    then
-        echo "Building Hwloc..."
-        cd $TMPDIR
-        wget https://www.open-mpi.org/software/hwloc/v1.11/downloads/hwloc-1.11.5.tar.gz -O - | tar -zx
-        cd hwloc-1.11.5
-        ./configure --prefix=$PREFIX
-        make -j 1 || { echo 'HWLOC installation failed' ; exit 1; }
-        make install
-    else
-        echo "####################"
-        echo "hwloc NOT FOUND"
-        echo "Please download it from: https://www.open-mpi.org/software/hwloc/v1.11/downloads/hwloc-1.11.5.tar.gz"
-        echo "After installing it, set the proper PKG_CONFIG_PATH variable"
-        echo ""
-        err=1
-    fi
-fi
+#if pkg-config --exists hwloc
+#then
+#    _LOCATION=`pkg-config --variable=prefix hwloc`
+#    echo "hwloc FOUND in [$_LOCATION]"
+#else
+#    if [ "$BUILD_DEPENDENCIES" == "true" ]
+#    then
+#        echo "Building Hwloc..."
+#        cd $TMPDIR
+#        wget https://www.open-mpi.org/software/hwloc/v1.11/downloads/hwloc-1.11.5.tar.gz -O - | tar -zx
+#        cd hwloc-1.11.5
+#        ./configure --prefix=$PREFIX
+#        make -j 1 || { echo 'HWLOC installation failed' ; exit 1; }
+#        make install
+#    else
+#        echo "####################"
+#        echo "hwloc NOT FOUND"
+#        echo "Please download it from: https://www.open-mpi.org/software/hwloc/v1.11/downloads/hwloc-1.11.5.tar.gz"
+#        echo "After installing it, set the proper PKG_CONFIG_PATH variable"
+#        echo ""
+#        err=1
+#    fi
+#fi
 
 # StarPU
 if pkg-config --exists --atleast-version=1.2 libstarpu
@@ -278,7 +278,8 @@ else
         echo "Building CHAMELEON..."
         cd $BASEDIR/src/hicma/chameleon
         mkdir -p build && cd build
-        cmake .. -DCHAMELEON_USE_MPI=$MPIVALUE -DCHAMELEON_USE_CUDA=$CUDAVALUE -DCHAMELEON_ENABLE_EXAMPLE=OFF -DCHAMELEON_ENABLE_TESTING=OFF -DCHAMELEON_ENABLE_TIMING=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$PREFIX   -DBLAS_LIBRARIES="-L${MKLROOT}/lib -Wl,-rpath,${MKLROOT}/lib -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl"
+        cmake .. -DCHAMELEON_USE_MPI=$MPIVALUE -DCHAMELEON_USE_CUDA=$CUDAVALUE -DCHAMELEON_ENABLE_EXAMPLE=OFF -DCHAMELEON_ENABLE_TESTING=OFF -DCHAMELEON_ENABLE_TIMING=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$PREFIX   -DBLAS_LIBRARIES="-L${MKLROOT}/lib -Wl,-rpath,${MKLROOT}/lib -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl" -DCBLAS_DIR="${MKLROOT}" -DLAPACKE_DIR="${MKLROOT}"
+
         make -j 1 || { echo 'CHAMELEON installation failed' ; exit 1; }
         make install
     else
